import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
// import { ClerkProvider } from "@clerk/nextjs";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
     <body className={inter.className}>
      <AuthProvider>
      {children}
      </AuthProvider>
      </body> 
    </html>
  
  );
}
